sensors:
  - default_sensor
  - kinect_depthimage
default_sensor:
  far_clipping_plane_distance: 1.0
  filtered_cloud_topic: filtered_cloud
  image_topic: /camera/depth/color/points
  max_update_rate: 10.0
  near_clipping_plane_distance: 0.3
  padding_offset: 0.03
  padding_scale: 1.0
  queue_size: 5
  sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
  shadow_threshold: 0.2
kinect_depthimage:
  far_clipping_plane_distance: 1.0
  filtered_cloud_topic: filtered_cloud
  image_topic: /camera/depth/image_rect_raw
  max_update_rate: 10.0
  near_clipping_plane_distance: 0.3
  padding_offset: 0.03
  padding_scale: 1.0
  queue_size: 5
  sensor_plugin: occupancy_map_monitor/DepthImageOctomapUpdater
  shadow_threshold: 0.2